---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  labels:
    app: webapp
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v2.0.0
  template:
    metadata:
      labels:
        app: webapp
        version: v2.0.0
    spec:
      containers:
      - name: webapp
        image: airodua/webapp:2.0.0
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "2.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
  labels:
    app: webapp
    version: v2.0.0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: webapp
    version: v2.0.0
